sudo: true
language: c++
dist: focal
env:
  - CUDA=10.1.105-1
addons:
  apt:
    packages:
      - g++-8
      - cmake
      - libopencv-dev 
      - python3-opencv
      - python3-pip
      - libboost-all-dev
      - wget
      - nvidia-cuda-toolkit
script:
  - export CC=/usr/bin/gcc-8
  - export CXX=/usr/bin/g++-8
  - wget https://dl.bintray.com/boostorg/release/1.75.0/source/boost_1_75_0.tar.gz
  - tar xf boost_1_75_0.tar.gz
  - cd boost_1_75_0
  - ./bootstrap.sh --with-python=/usr/bin/python3
  - ./b2 --with-python link=static cxxflags="-std=c++11 -fPIC" variant=release stage
  - sudo ./b2 --with-python link=static cxxflags="-std=c++11 -fPIC" variant=release install
  - cd ..
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make
  - sudo make install
  - cd ..
  - rm data/output_512x409_trimap_iter_5_gamma_10.png
  - python3 src/main_grabcut.py --image data/tool_512x409.png --trimap data/trimap_512x409.png --output data/output_512x409_trimap_iter_5_gamma_10.png --iter 5 --gamma 10.0
  - ls data/output_512x409_trimap_iter_5_gamma_10.png
  - rm data/output_512x409_trimap_iter_5_gamma_10.png
  - build/bin/main_grabcut --image data/tool_512x409.png --trimap data/trimap_512x409.png --output data/output_512x409_trimap_iter_5_gamma_10.png --iter 5 --gamma 10.0
  - ls data/output_512x409_trimap_iter_5_gamma_10.png
